### ISSUE TITLE
No need to refresh token if it's already set in config

### ISSUE THREAD

**Issue by Ajaxy** [gazay/odnoklassniki#2]
You can pass `access_token` to config or `Odnoklassniki::Client` initializer, but it will be overwritten at the first request because of `refreshed = false` param.

**Comment by gazay** [comment]
Токен в одноклассниках устаревает достаточно быстро, толи полчаса толи день, в доках у них описано. При этом для рефреша себя он является валидным, сколько бы времени ни прошло, сколько бы раз его не рефрешили. Таким образом я на всякий случай всегда рефрешу токен при первом запросе

**Comment by Ajaxy** [comment]
У меня рефреш не работает. Присваивается `nil`, поэтому никакие запросы не проходят.
Возможно причина в том, что я получаю токен из приложения на клиенте, через http://apiok.ru/wiki/pages/viewpage.action?pageId=81822117 а потом передаю его для проверки на сервер.

**Comment by incubus** [comment]
У одноклассников появился в настройках "Вечный access_token", поэтому все же есть смысл не рефрешить при явном наличии token или сделать это опциональным.
